version: '2'

services:

    web:
      restart: always
      build: ./web
      command: gunicorn -w 2 -b :5000 run:app
      expose:
        - "5000"
      volumes:
        - ./web/micblog:/micblog
        - ./web/micblog/app/static:/micblog/app/static

    nginx:
      restart: always
      build: ./nginx 
      ports:
        - "8090:8090"
      volumes:
        - ./web/micblog/app/static:/micblog/app/static
      volumes_from:
        - web
      links:
        - web:web
