# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 13:08
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_courseorg_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='has_authentication',
            field=models.BooleanField(default=False, verbose_name='\u8ba4\u8bc1'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='has_gold',
            field=models.BooleanField(default=False, verbose_name='\u91d1\u724c'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u673a\u6784\u63cf\u8ff0'),
        ),
    ]
