# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_teacher_has_gold_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='star_scope_nums',
            field=models.FloatField(default=0.0, verbose_name='\u63a8\u8350\u6307\u6570'),
        ),
    ]
