# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_courseorg_star_scope_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='star_scope_nums',
            field=models.FloatField(choices=[('0.0', '0\u661f'), ('0.5', '0.5\u661f'), ('1.0', '1\u661f'), ('1.5', '1.5\u661f'), ('2.0', '2.0\u661f'), ('2.5', '2.5\u661f'), ('3.0', '3.0\u661f'), ('3.5', '3.5\u661f'), ('4.0', '4.0\u661f'), ('4.5', '4.5\u661f'), ('5.0', '5\u661f')], default=0.0, verbose_name='\u63a8\u8350\u6307\u6570'),
        ),
    ]
